In [2]:
import tensorflow as tf
import numpy as np

In [3]:
Image = np.array([[3.0,5,3,4,1],[5,3,2,1,1],[5,1,4,1,0],[2,1,0,0,3]])
filter11=np.array([[3.0,1,2],[1,4,5],[1,1,0]])

In [4]:
print(Image)

[[3. 5. 3. 4. 1.]
 [5. 3. 2. 1. 1.]
 [5. 1. 4. 1. 0.]
 [2. 1. 0. 0. 3.]]


In [5]:
print(filter11)

[[3. 1. 2.]
 [1. 4. 5.]
 [1. 1. 0.]]


In [14]:
Image_tf=tf.reshape(Image,[-1,4,5,1])
kernel_tf=tf.reshape(filter11,[3,3,1,1])
conv1=tf.nn.conv2d(Image_tf,kernel_tf,strides=[1,1,1,1],padding="SAME")

#pool1=tf.nn.max_pool(Image_tf,ksize=[1,2,2,1],strides=[1,2,2,1],padding="SAME")
with tf.Session()as sess:
    conv1_value=sess.run(conv1)
    pool1_value=sess.run(pool1)
    print(conv1_value.shape)
    print(conv1_value)
   # print(pool1_value.shape)
    #print(pool1_value)

(1, 4, 5, 1)
[[[[42.]
   [46.]
   [42.]
   [27.]
   [10.]]

  [[53.]
   [53.]
   [47.]
   [31.]
   [19.]]

  [[38.]
   [54.]
   [36.]
   [17.]
   [ 8.]]

  [[20.]
   [30.]
   [10.]
   [28.]
   [15.]]]]


In [16]:
Image_tf=tf.reshape(Image,[-1,4,5,1])
kernel_tf=tf.reshape(filter11,[3,3,1,1])
#conv1=tf.nn.conv2d(Image_tf,kernel_tf,strides=[1,1,1,1],padding="SAME")

pool1=tf.nn.max_pool(Image_tf,ksize=[1,2,2,1],strides=[1,2,2,1],padding="SAME")
with tf.Session()as sess:
    conv1_value=sess.run(conv1)
    pool1_value=sess.run(pool1)
  #  print(conv1_value.shape)
   # print(conv1_value)
    print(pool1_value.shape)
    print(pool1_value)

(1, 2, 3, 1)
[[[[5.]
   [4.]
   [1.]]

  [[5.]
   [4.]
   [3.]]]]
