In [19]:
import tensorflow as tf

In [20]:
# read dataset and print from file1 
dataset = tf.data.TextLineDataset("file1.txt")
dataset = dataset.map(lambda string: tf.string_to_number(tf.string_split([string]).values))

iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

with tf.Session() as sess:
   for i in range(3):
       print(sess.run(next_element))

[1. 2. 3.]
[ 5.  2. 33.]
[4. 5. 2.]


In [21]:
# read dataset and print from iris (train and test) (such as above but by using function)
def readtxt(filename):
    dataset = tf.data.TextLineDataset(filename)
    dataset = dataset.map(lambda string: tf.string_to_number(tf.string_split([string]).values))

    iterator = dataset.make_one_shot_iterator()
    next_element = iterator.get_next()
    return next_element
           
def printdata(data,n):
    with tf.Session() as sess:
        for i in range(n):
            print(sess.run(data))

In [22]:
training_attributes=readtxt("iris_train_features.txt")
training_label=readtxt("iris_train_label.txt")
test_attributes=readtxt("iris_test_features.txt")
test_label=readtxt("iris_test_label.txt")
print("-------training-------")
printdata(training_attributes,3)
print("-------training_label-------")
printdata(training_label,3)
print("-------test-------")
printdata(test_attributes,3)
print("-------test_label-------")
printdata(test_label,3)



-------training-------
[4.9 3.  1.4 0.2]
[7.6 3.  6.6 2.1]
[4.9 3.1 1.5 0.1]
-------training_label-------
[0. 0. 1.]
[1. 0. 0.]
[0. 0. 1.]
-------test-------
[5.4 3.4 1.5 0.4]
[5.  3.4 1.6 0.4]
[7.1 3.  5.9 2.1]
-------test_label-------
[0. 0. 1.]
[0. 0. 1.]
[1. 0. 0.]
